theme: jekyll-theme-minimal
title: Gianni Saporiti's Website!
description: A collection of random projects and tools that I've been working on. Mostly related to the cryptocurrency, financial and data analysis spaces.
